import Head from 'next/head'
import { signInWithGoogle } from '../Utils/firebase'
import { useRouter } from 'next/router'

export default function Home() {

  const router = useRouter();

  const OnGooglePressed = async () => {
    try {
      let res = await signInWithGoogle();
      if(res) router.push('/home');
    } catch (error) {
      console.log(error);
    }   
  }

  return (
    <div>
      <Head>
        <title>U-Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={OnGooglePressed}>Sign In With Google</button>

      <br />
      <br />
      <h1>Test Change</h1>
      <br />
      <h2><b>This is a new feature</b></h2>
      <br />
      <h2>AWS is cool</h2>
      
    </div>
  )
}
