import Head from 'next/head'
import Listings from './home/Listings'

export default function Home() {


  return (
    <div>
      <Head>
        <title>U-Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Listings />

    </div>
  )
}
